export const INIT_JOKES = 'INIT_JOKES';
export const GET_JOKES = 'GET_JOKES';
export const SELECT_JOKE = 'SELECT_JOKE';
export const FAVOURITE_JOKE = 'FAVOURITE_JOKE';
export const FETCH_JOKES_REQUEST = 'FETCH_JOKES_REQUEST';
export const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
export const FETCH_JOKES_FAILURE = 'FETCH_JOKES_FAILURE';
